


CREATE USER 'ifeb'@'%' IDENTIFIED VIA mysql_native_password USING '***';GRANT USAGE ON *.* TO 'ifeb'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;CREATE DATABASE IF NOT EXISTS `ifeb`;GRANT ALL PRIVILEGES ON `ifeb`.* TO 'ifeb'@'%';GRANT ALL PRIVILEGES ON `ifeb\_%`.* TO 'ifeb'@'%';
